CREATE TABLE InfoForum(
      Unique_Identifier text PRIMARY KEY,
      Date_of_Birth text,
			Postal_Code text,
      Start_Date_of_Service text,
			Language_of_Service text,
      Official_Language_of_Preference text,
			Type_of_Institution text,Referred_By text,
			Services_Received text,
      Total_Length_of_Orientation text,
      Total_Length_of_Orientation_Hours text,
			Total_Length_of_Orientation_Minutes text,
      Number_of_Clients_in_Group text,
			Directed_at_a_specific text,
      Children text,
			Youth text,
      Seniors text,
      Gender_specific text,
			Refugees text,
      Ethnic text,
			Deaf_or_Hard_of_Hearing text,
      Blind_or_Partially_Sighted text,
			LGBTQ text,
      Families text,
			Clients_with_other_impairments text,
      Clients_with_international_training_in_a_regulated_profession text,
			Clients_with_international_training_in_a_regulated_trade text,
      Official_Language_minorities text,
			Overview_of_Canada text,Overview_of_Canada_Referrals text,
      Sources_of_Information text,Sources_of_Information_Referrals text,
			Rights_and_Freedoms text,
      Rights_and_Freedoms_Referrals text,
      Canadian_Law_and_Justice text,
      Important_Documents text,
			Important_Documents_Referrals text,
      Improving_English_or_French text,
      Improving_English_or_French_Referrals text,
      Employment_and_Income text,
      Employment_and_Income_Referrals text,
			Education text
      ,Education_Referrals text,
      Housing text,
      Housing_Referrals text,
      Health text,
      Health_Referrals text,
      Money_and_Finances text,
			Money_and_Finances_Referrals text,
      Transportation text,
      Transportation_Referrals text,
      Communications_and_Media text,
      Communications_and_Media_Referrals text,
			Community_Engagement text,
      Community_Engagement_Referrals text,
      Becoming_a_Canadian_Citizen text,
      Becoming_a_Canadian_Citizen_Referrals text,
      Interpersonal_Conflict text,
			Interpersonal_Conflict_Referrals text,
      Was_Essential_Skills_and_Aptitude_Training_Received text,
      Computer_skills text,Document_Use text,
			Interpersonal_Skills_and_Workplace_Culture text,
      Leadership_Training text,
      Numeracy text,	Was_Life_Skills text,
			Life_Skills text,
      Rights_and_Responsibilities_of_Citizenship text,
      Support_Services_Received text,Care_for_Newcomer_Children text,
			Child_1_Age text,
      Child_1_Type_of_Care text,
      Child_2_Age text,
      Child_2_Type_of_Care text,
      Child_3_Age text,
      Child_3_Type_of_Care text,
      Child_4_Age text,
      Child_4_Type_of_Care text,
			Child_5_Age text,
      Child_5_Type_of_Care text,
      Transportation_2 text,
      Provisions_for_Disabilities text,
      Translation text,
      Between_1 text,
      And_1 text,
      Interpretation text,
      Between_2 text,
      And_2 text,
			Crisis_Counselling text,
      End_Date_of_Service text,
      Reason_for_update text
);
